{% set name = "pycomm3" %}
{% set version = "1.2.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycomm3-{{ version }}.tar.gz
  sha256: 9a47c91e628c2fddfd0c24478f4700c5eba278d868a116b853bc89dc80879206

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pycomm3
    - pycomm3.cip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ottowayi/pycomm3
  summary: A Python Ethernet/IP library for communicating with Allen-Bradley PLCs.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ruben-arts
