{% set name = "pycomm3" %}
{% set version = "1.2.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycomm3-{{ version }}.tar.gz
  sha256: cb6f41c49269e5ba7dd9c5ded319b8f9964a26c04246a52f2ebd906af04f3c1a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pycomm3
    - pycomm3.cip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ottowayi/pycomm3
  summary: A Python Ethernet/IP library for communicating with Allen-Bradley PLCs.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ruben-arts
