{% set name = "pycomm3" %}
{% set version = "1.2.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycomm3-{{ version }}.tar.gz
  sha256: fa9cff7c7dd502f26a4756f9a87c5cad2c5f6fbea9a5ce3e475e7fece230ea0b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pycomm3
    - pycomm3.cip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ottowayi/pycomm3
  summary: A Python Ethernet/IP library for communicating with Allen-Bradley PLCs.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ruben-arts
